# Generated by Django 5.1.7 on 2025-04-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Private projects are only visible to invited freelancers', verbose_name='Private Project'),
        ),
    ]
